# Generated by Django 4.2.5 on 2023-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsdata', '0003_alter_clientdata_total_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Paid'),
        ),
    ]
