# Generated by Django 4.2.5 on 2023-09-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsdata', '0006_alter_clientdata_total_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='to_pay',
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='total_deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Total Deuda'),
        ),
    ]
