# Generated by Django 4.2.5 on 2023-09-19 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientsdata', '0007_remove_clientdata_to_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
