# Generated by Django 4.2.5 on 2023-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsdata', '0002_alter_clientdata_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='total_deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Deuda'),
        ),
    ]
